### ISSUE TITLE
Unable to add new Investigation (KCI Dev)

### ISSUE THREAD

**Issue by rssidlowski** [rssidlowski/Pollution_Source_Tracking#118]
On http://vm-1108s08/pstwebapi/index.aspx, attempting to add new investigation and the screen just says loading.
![screenloading](https://cloud.githubusercontent.com/assets/5039052/5900077/85e10b66-a532-11e4-8579-8ec10e6fd4d4.GIF)

Similarly, when I select by watershed and attempt to view on the map I get it just loading.
![selectbywatershed](https://cloud.githubusercontent.com/assets/5039052/5900106/ebd8d782-a532-11e4-99b0-de6ebd0b27e2.GIF)

![selectbywatershedclickmap](https://cloud.githubusercontent.com/assets/5039052/5900110/eea4b936-a532-11e4-8d62-811e0e1c0be9.GIF)

![selectbywatershedloading](https://cloud.githubusercontent.com/assets/5039052/5900112/f114fbe0-a532-11e4-901a-2410e94fedf7.GIF)

**Comment by gjmkelly** [comment]
This is not happening for me (and I have not touched these parts of the app code).  I think maybe what you observed is because the base map is loading very slowly.  I'm not going to worry about that in KCI test.  (I do almost all the development/testing with only the PST layer on for efficiency).  So, let it sit for a while with the "loading" spinning and see if it eventually works.  If it consistently fails for you, I'll look into it further.

**Comment by rssidlowski** [comment]
This works find in COB dev so closing for now.
