### ISSUE TITLE
Application revision to create, save and use sample IDs not based on OBJECTID

### ISSUE THREAD

**Issue by gerrykelly** [rssidlowski/Pollution_Source_Tracking#163]
The part of the app that changed should only involve processes on sample creation and the first time the sample is saved afterward, if ever.  So, the real test is only for new samples you add and edit.  The old ones where sampleID=ObjectID are not worth testing.

However, I had to recreate a big piece of the web services part because Visual Studio rejected the updated old database objects.  No reason to think anything there would not work like before, but I quick touch on each app function (not at any level of detail, just basic select save, etc) is in order.

**Comment by rssidlowski** [comment]
Looks good.  I am seeing something strange when I add a sample and I previously selected me as personnel.  The next sample I create I need to select someone else and then select me before my name appears in the personnel list when I can then click on the Add button.  so I see my name in the drop down list with a check mark next to it but it doesn't put the name in the 'pick personnel to add' space.
Otherwise ok, I added investigations and samples just fine.
