### ISSUE TITLE
Update Investigation Sample hanging

### ISSUE THREAD

**Issue by rssidlowski** [rssidlowski/Pollution_Source_Tracking#166]
This was reported by Matt at COB. Verified in dev and prod.
If select a sample from the map using the Identify button and select a sample, when attempting to edit just get Loading....
Can update a sample from other selection methods, but not from the Identify on the map.

**Comment by gerrykelly** [comment]
This was failing for a couple reasons.  The samples form gets populated in a different manner when the info comes from the map selection.  You'll notice that where the form usually has blank text boxes for nulls, when from the map select it has Null spelled out.  Rather than trying to correct this, I just added code to ignore it on the save operation.  Seems to work.

**Comment by rssidlowski** [comment]
Still not working in dev.  Brought up sample 19435 from I on map and updated comments field and just loading.

**Comment by gerrykelly** [comment]
I just tried the same thing a few times, including never using the form-based selection at all, only the map and it works fine everytime for me.

**Comment by rssidlowski** [comment]
Still failing.  I brought up sample 21957 from the map using the Identify, added a space to the comments and get the loading....
![iloading](https://cloud.githubusercontent.com/assets/5039052/8036217/6dff3a04-0dc4-11e5-9098-d5b1bc7fdbaf.PNG)

**Comment by gerrykelly** [comment]
It looks like you are testing this in the prod app, not dev.

**Comment by rssidlowski** [comment]
Verified in cobdev.

**Comment by rssidlowski** [comment]
Verified in prod.
