### ISSUE TITLE
Reports: several issues with reports

### ISSUE THREAD

**Issue by rssidlowski** [rssidlowski/Pollution_Source_Tracking#189]
Complaints: cannot view printable report
Investigations by Status by date range: cannot view printable report
Investigations by Complainant for date range: cannot view printable report
Investigation per Origin by year: FY equation is wrong (compare it to Investigations per status by Month which has the correct fiscal year data)
Investigations per Status by year: FY equation is wrong
Investigations per Watershed by year: FY equation is wrong
Investiations per Problem Type by year: FY equation is wrong
PST by Problem Type and Status: FY equation is wrong

In the report PST Tracking Sheet the
 GPS coordinates do not appear.  We do not enter coordinates, does the program store coordinates with the points, if so can this be captured an put onto this report.

![pstreport](https://cloud.githubusercontent.com/assets/5039052/10953112/5a07b254-8314-11e5-840c-8ba5ca0412a0.jpg)

**Comment by gerrykelly** [comment]
1.  Most of the problem for the three “cannot view printable report” issues was that the data operations failed now that there a samples related to multiple investigations in the database.  I only fixed this for production since there is no sense in going back to dev.
   These three reports needed to be moved to the http://dpwview.baltimorecity.gov/sduo/*** 
   URL.  So, we need to ask Jesse to repoint them from the UI like he has done for some other reports that were moved.  If you would like to test before, I can send you some report URLs.
2.  The 5 noted FY problems are fixed in prod.
3.  Their legacy data had lat/long values, but – while we migrated them – this was not a part of the app.  I redeveloped the app to calculate lat/long for new and moved sample points.  This is implemented in dev.  You won’t see any difference in the app, unless there is some error.  So please test a few create new and move samples and make sure things work like they used to.  If so, I’ll move it to prod.  I bulk-calculated lat/long for all existing samples in prod.  You can see an example of the values in the report: http://dpwview.baltimorecity.gov/SDUO/rptPSTtrack.aspx?wshed=Patapsco&date1=1/1/2011&date2=12/12/2013  Note that I changed the labels to make it clear these are lat/long coordinates.  When I update prod, I should calculate lat/long for any samples since added or moved.
