### ISSUE TITLE
Data: add complainant category

### ISSUE THREAD

**Issue by rssidlowski** [rssidlowski/Pollution_Source_Tracking#67]
Add a new field "COMPLAINANT_NAME" to the PST_Investigations table.   Update the data migration to have the complainants go into this field.
The table "PST_ComplainantSourceCodes" and associated field in PST_Investigations will be used for categories of complainants.
We may need to make a 'best guess' on the categories to include at a minimum the following:
Blue Water Baltimore
Center for Watershed Protection
Citizen
City
Contractor
EPA
HRWA
Other
MDE
WQMS
WWE

Once done, pass to Lu to have him add to the application a new field after stream name and before Complainant called Complainant Category in investigation detail screen:
![addcatcode](https://cloud.githubusercontent.com/assets/5039052/5015105/cc5d9c30-6a68-11e4-8c13-061ac8905d89.GIF)

**Comment by kanglu666** [comment]
Are  the [COMPLAINANT_ID] and the [COMPLAINANT_NAME] fields in INVESTIGATION both associated  with PST_ComplainantSourceCodes? if yes, i think they are duplicate

**Comment by gerrykelly** [comment]
No.  The "new" COMPLAINANT_NAME field is text for the specific name entered for the complainant(s) for the investigation -- like Lu Kang or Gerry Kelly.  With how the PST_ComplainantSourceCodes table now works the COMPLAINANT_ID for the investigation would be "3" -- for "Citizen".  (since this was not the original approach, the values for existing records are inaccurate, but will be made correct in the final migration)

**Comment by rssidlowski** [comment]
Lu, please add the field in the user interface.

**Comment by kanglu666** [comment]
done

**Comment by rssidlowski** [comment]
Why do you have placeholders in the complainant dropdown list?

**Comment by gerrykelly** [comment]
because we used to have many more values for complainants before we consolidated to the categories we have now.  Those no longer to be used values from the investigations table still need to map to something.  I'll clean it up for the final migration, but it's not worth wasting the time now (it'll probably take a few hours to process their complainant values to the new aggregated values)

**Comment by rssidlowski** [comment]
This needs to be corrected to be able to verify reports - many have complainant with placeholders.

**Comment by rssidlowski** [comment]
Verified.
